# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeManageFirstNumber', models.CharField(max_length=20)),
                ('codeManageSecondNumber', models.CharField(max_length=20)),
                ('codeManageCodeName', models.CharField(max_length=30)),
                ('codeManageCodeAuthor', models.CharField(max_length=20)),
                ('codeManageIsShare', models.BooleanField()),
                ('codeManageLanguage', models.CharField(max_length=20)),
                ('codeManageSearchTimes', models.CharField(max_length=20)),
                ('codeManageCheckTimes', models.CharField(max_length=20)),
                ('codeManageDownloadTimes', models.CharField(max_length=20)),
                ('codeManageCodeExplain', models.TextField()),
                ('codeManageSavePosition', models.CharField(max_length=254)),
                ('codeManageUploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='codeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeTagName', models.CharField(max_length=20)),
                ('codeTagClickTimes', models.CharField(max_length=20)),
                ('codeTagLastClick', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='codeTagRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeTagRelationiCodeID', models.CharField(max_length=20)),
                ('codeTagRelationTagID', models.CharField(max_length=20)),
                ('codeTagRelationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
