# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codeManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeLanguageType', models.CharField(max_length=20)),
                ('codeLanguageTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
