# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codeManage', '0002_codelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemanage',
            name='codeManageMainFlag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
