# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codeManage', '0004_codemanage_codemanageisdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeDiscuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeDiscussSecondNumber', models.CharField(max_length=20)),
                ('codeDiscussUserCreateID', models.CharField(max_length=20)),
                ('codeDiscussUserReplyID', models.CharField(max_length=20)),
                ('codeDiscussCreateDataTime', models.DateTimeField(auto_now_add=True)),
                ('codeDiscussIsDelete', models.BooleanField()),
            ],
        ),
    ]
