# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codeManage', '0005_codediscuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='codediscuss',
            name='codeDiscussContent',
            field=models.TextField(default='Very Good'),
            preserve_default=False,
        ),
    ]
