# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codeManage', '0006_codediscuss_codediscusscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemanage',
            name='codeManageCheckTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codemanage',
            name='codeManageDownloadTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codemanage',
            name='codeManageSearchTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codetag',
            name='codeTagClickTimes',
            field=models.IntegerField(),
        ),
    ]
