# Generated by Django 2.1.2 on 2021-01-15 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBaseManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='论文名称')),
                ('author', models.CharField(max_length=200, verbose_name='论文作者')),
                ('paper_file', models.FileField(upload_to='app_paper_view', verbose_name='论文存储')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '论文基础管理数据库',
                'verbose_name_plural': '论文基础管理数据库',
            },
        ),
        migrations.CreateModel(
            name='PaperCodeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('add_version', models.CharField(max_length=10, verbose_name='代码版本')),
            ],
            options={
                'verbose_name': '论文用户自定义代码',
                'verbose_name_plural': '论文用户自定义代码',
            },
        ),
        migrations.CreateModel(
            name='PaperConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='会议名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '会议、期刊',
                'verbose_name_plural': '会议、期刊',
            },
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='关键字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
            },
        ),
        migrations.CreateModel(
            name='PaperKeywordConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '关键字连接',
                'verbose_name_plural': '关键字连接',
            },
        ),
        migrations.CreateModel(
            name='PaperReadManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('add_type', models.IntegerField(choices=[(1, '时间自动保存'), (2, '点击自动保存')], verbose_name='操作类型')),
                ('read_process', models.IntegerField(default=1, verbose_name='浏览进度（记录页数）')),
                ('read_zoom', models.IntegerField(default=100, verbose_name='缩放大小')),
            ],
            options={
                'verbose_name': '论文浏览进度',
                'verbose_name_plural': '论文浏览进度',
            },
        ),
        migrations.CreateModel(
            name='PaperReviewManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***')], verbose_name='评价')),
                ('review_text', models.CharField(max_length=200, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '论文用户评论',
                'verbose_name_plural': '论文用户评论',
            },
        ),
        migrations.CreateModel(
            name='PaperTransCodeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('trans_file', models.FileField(upload_to='app_paper_view', verbose_name='论文翻译存储（markdown格式）')),
                ('paper_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paper_view.PaperBaseManage', verbose_name='所属论文')),
            ],
            options={
                'verbose_name': '论文翻译',
                'verbose_name_plural': '论文翻译',
            },
        ),
    ]
