# Generated by Django 2.2 on 2021-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_paper_view', '0002_auto_20210115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperbasemanage',
            name='paper_file',
            field=models.FileField(upload_to='static_files/paper_file_save', verbose_name='论文存储'),
        ),
    ]
