# Generated by Django 2.2 on 2021-02-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_paper_view', '0003_auto_20210212_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbasemanage',
            name='conference_year',
            field=models.IntegerField(default=2000, max_length=5, verbose_name='论文年份'),
            preserve_default=False,
        ),
    ]
