# Generated by Django 2.2 on 2021-04-19 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_paper_view', '0005_auto_20210330_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_text', models.CharField(max_length=10, verbose_name='标签内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '论文所属的标签',
                'verbose_name_plural': '论文所属的标签',
            },
        ),
        migrations.CreateModel(
            name='PaperLabelConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sub_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paper_view.PaperLabel', verbose_name='所属标签')),
                ('sub_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paper_view.PaperBaseManage', verbose_name='所属论文')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '论文与标签关联',
                'verbose_name_plural': '论文与标签关联',
            },
        ),
    ]
