# Generated by Django 2.2 on 2021-02-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_manage', '0002_auto_20210212_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user_token',
            field=models.CharField(max_length=200, verbose_name='用户令牌'),
        ),
    ]
