# Generated by Django 2.2 on 2021-02-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_manage', '0003_auto_20210212_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='is_alive',
            field=models.IntegerField(choices=[(0, '有效'), (1, '失效'), (2, '已注销')], default=0, verbose_name='令牌是否有效'),
        ),
    ]
