# Generated by Django 2.2 on 2021-03-30 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateForTODOmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板的名字')),
                ('describe', models.CharField(max_length=200, verbose_name='模板的描述')),
                ('is_shared', models.IntegerField(choices=[(0, '不共享'), (1, '共享')], verbose_name='是否共享')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '模板管理',
                'verbose_name_plural': '模板管理',
            },
        ),
        migrations.CreateModel(
            name='ToDoListTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='待办内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sub_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_study_view.TemplateForTODOmanage', verbose_name='所属模板类')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '待办事项的模板',
                'verbose_name_plural': '待办事项的模板',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateField(auto_now=True, verbose_name='添加时间')),
                ('content', models.CharField(max_length=200, verbose_name='待办内容')),
                ('is_complete', models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], verbose_name='是否完成')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
            },
        ),
    ]
