# Generated by Django 2.2 on 2021-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study_view', '0002_todolistlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolistlog',
            options={'verbose_name': '待办事项的日志', 'verbose_name_plural': '待办事项的日志'},
        ),
        migrations.AlterField(
            model_name='todolistlog',
            name='content',
            field=models.CharField(max_length=16000, verbose_name='待办内容'),
        ),
    ]
