# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selfPartMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfPartMessageCreateTime', models.DateTimeField(auto_now_add=True)),
                ('selfPartMessageSendUserID', models.CharField(max_length=20)),
                ('selfPartMessageReceUserID', models.CharField(max_length=20)),
                ('selfPartMessageIsNew', models.BooleanField()),
                ('selfPartMessageContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='selfPartMyFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfPartFriendDoneTime', models.DateTimeField(auto_now_add=True)),
                ('selfPartOwnID', models.CharField(max_length=20)),
                ('selfPartFriendID', models.CharField(max_length=20)),
            ],
        ),
    ]
