# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfPart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfPartFocusRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfPartFocusRelationOwnID', models.CharField(max_length=20)),
                ('selfPartFocusRelationUserID', models.CharField(max_length=20)),
                ('selfPartFocusRelationCodeID', models.CharField(max_length=20)),
                ('selfPartFocusRelationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
