# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfPart', '0002_selfpartfocusrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfPartUserDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfPartUserDynamicUserID', models.CharField(max_length=10)),
                ('selfPartUserDynamicType', models.CharField(max_length=30)),
                ('selfPartUserDynamicPic', models.CharField(max_length=20)),
                ('selfPartUserDynamicExplain', models.TextField()),
                ('selfPartUserDynamicCodeID', models.CharField(max_length=10)),
                ('selfPartUserDynamicTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
