# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfPart', '0003_selfpartuserdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfpartmessage',
            name='selfPartMessageIsDelete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
