# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfPart', '0004_selfpartmessage_selfpartmessageisdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfpartmessage',
            old_name='selfPartMessageIsDelete',
            new_name='selfPartMessageIsDeleteByRece',
        ),
        migrations.AddField(
            model_name='selfpartmessage',
            name='selfPartMessageIsDeleteBySend',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
