# Generated by Django 2.2 on 2021-04-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_activities_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadmintonOrder',
        ),
    ]
