# Generated by Django 2.2 on 2021-04-07 08:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_activities_view', '0002_delete_badmintonorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_order_person', models.CharField(max_length=200, verbose_name='预定人名字')),
                ('number_of_venue', models.IntegerField(verbose_name='球场的号码')),
                ('date_of_order', models.CharField(max_length=2000, verbose_name='预定时间')),
                ('time_quantum', models.IntegerField(choices=[(1, '早上'), (2, '中午'), (3, '晚上')], verbose_name='早中晚')),
                ('time_of_order', models.IntegerField(verbose_name='时间段')),
                ('pic_of_order', models.FileField(upload_to='static_files/badminton_order_pic_save', verbose_name='预定截图')),
                ('remarks', models.CharField(max_length=2000, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '羽毛球场馆预定',
                'verbose_name_plural': '羽毛球场馆预定',
            },
        ),
    ]
